client_config_backend: file
client_config:
    client_id: 616101314731-626d1ev7m5i2lvjigui4s8ahilnme2k3.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install